name: press
description: "Mobile application that detect and measure user gestures starting from press pressure, position to rate and many. with all love"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.3
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.1
  syncfusion_flutter_charts: ^28.1.35
  permission_handler: ^11.3.1
  excel: ^4.0.6
  downloadsfolder: ^1.2.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
      - assets/images/
      - assets/jsons/
      - assets/dark-images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
